# vi: et ts=2 sts=2 ft=ansible
---
- name: Create sudo group
  ansible.builtin.group:
    name: sudo

- name: Grant passwordless sudo to sudo group
  ansible.builtin.template:
    src: etc/sudoers.d/99-sudo-nopasswd
    dest: /etc/sudoers.d/99-sudo-nopasswd
    mode: "0644"

- name: Create opusers group
  ansible.builtin.group:
    name: opusers

- name: Create operator users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    group: opusers
    groups: "{{ item.groups | default([]) + ['sudo'] }}"
  loop: "{{ users.operators }}"

- name: Set authorized keys to operator users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ users.operators }}"
  when: item.key is defined
