# vi: et ts=2 sts=2 ft=ansible
---
- name: Create wheel group
  ansible.builtin.group:
    name: wheel

- name: Grant passwordless sudo to wheel group
  ansible.builtin.template:
    src: etc/sudoers.d/99-wheel-nopasswd
    dest: /etc/sudoers.d/99-wheel-nopasswd
    mode: "0644"

- name: Create operators group
  ansible.builtin.group:
    name: operators

- name: Create operator users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    group: operators
    groups: "{{ item.groups | default([]) + ['wheel'] }}"
  loop: "{{ users.operators }}"

- name: Set authorized keys to operator users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ users.operators }}"
  when: item.key is defined
